### ISSUE TITLE
`process_dataset.py` is missing

### ISSUE THREAD

**Issue by binkjakub** [ml-jku/vnegnn#3]
I try to reproduce the results in the paper. However, I encountered a missing `process_dataset.py` script, which, as far as I'm concerned, is necessary to process the dataset. Could you please provide a preprocessing script and/or preprocessed datasets?

Thanks a bunch!

**Comment by fses91** [comment]
Hi,

I forgot to include that file in the public version, I apologize for that, I added the process_dataset.py file now.

The process_dataset.py, expects that the folders are in a specific structure, we will make this datasets available soon.

Best regards,
Florian

**Comment by 1874Mercury** [comment]
Great! When will the cleaned datasets be available?

**Comment by fses91** [comment]
Hi, 

I will try to upload it in the next couple of weeks.

Best regards,
Florian

**Comment by fangjingmu** [comment]
> Hi,
> 
> I will try to upload it in the next couple of weeks.
> 
> Best regards, Florian

Is the cleaned dataset avilable now?
