### ISSUE TITLE
how to use data.mdb  lock.mdb

### ISSUE THREAD

**Issue by 17dacheng** [ml-jku/vnegnn#5]
how to use data.mdb  lock.mdb to do multi-gpu inference, can you give a sample code?

**Comment by fses91** [comment]
Hi for the data.mdb you need to process the files before.
Best regards

**Comment by 17dacheng** [comment]
> Hi for the data.mdb you need to process the files before. Best regards

already have data.mdb lock.mdb file, how to use it for inference? is there any sample code
