### ISSUE TITLE
The test dataset code has no run.

### ISSUE THREAD

**Issue by 17dacheng** [ml-jku/vnegnn#6]
the test dataset code reported no run error   for run.config, could u give out how to modify?

# Run this from the root of the project
from src.models.egnn import EGNNClassifierGlobalNodeHetero
from hydra.utils import instantiate
import pytorch_lightning as pl

path_to_config = "/path/to_config/"
cfg = OmegaConf.create(run.config)

**Comment by fses91** [comment]
Hi,
please follow: https://github.com/ml-jku/vnegnn?tab=readme-ov-file#run-on-test-dataset
Best regards

**Comment by 17dacheng** [comment]
> https://github.com/ml-jku/vnegnn?tab=readme-ov-file#run-on-test-dataset

yes, it report error 'no run.config', the code doesn't import run
